import type { Metadata } from "next";
import { Lato } from 'next/font/google';
import "./globals.css";
import { Header } from "@/components/header";

const lato = Lato({
   subsets: ["latin"],
   weight: ['400', '700'],
   });

export const metadata: Metadata = {
  title: "Banco Itaú | Feito com você.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />
      </head>
      <body className={lato.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
